import Head from 'next/head'
import React, { useState } from 'react'
import { Col, Container, InputGroup, Row } from 'reactstrap'
import container from '@/styles/Containers.module.css'
import text from '@/styles/Texts.module.css'
import input from '@/styles/Inputs.module.css'
import button from '@/styles/Buttons.module.css'
import Image from 'next/image'
import { Button, Checkbox, Dropdown, Input } from '@nextui-org/react'
import Link from 'next/link'
import { CustomLink } from '@/Components/Texts'
import { UploadIcon } from '@/assets/Icons/UploadIcon'

export default function Cadastro() {
    const [selected, setSelected] = useState('Gênero')
    const [option, setOption] = useState(selected)
    return (
        <>
            <Head>
                <title>Story Teller</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/storyicon.ico" />
            </Head>
            <main>
                <Container fluid className={container.container_black}>
                    <Row className='h-100'>
                        <Col xs={12} md={8} className='d-flex flex-column align-items-center justify-content-center'>
                            <Row className='justify-content-center my-4'>
                                <Col>
                                    <span className={text.title_white}>Cadastre-se</span>
                                </Col>
                            </Row>
                            <Row className='justify-content-center'>
                                <Col xs={10}>
                                    <Row className='py-3'>
                                        <Col xs={12} md={6}>
                                            <Input
                                                size='sm'
                                                labelPlaceholder="Nome Completo"
                                                status="default"
                                                clearable
                                            />
                                        </Col>
                                        <Col xs={12} md={6}>
                                            <Input
                                                size='sm'
                                                labelPlaceholder="Username"
                                                status="default"
                                                clearable
                                            />
                                        </Col>
                                    </Row>
                                    <Row className='py-3'>
                                        <Col xs={12} md={6}>
                                            <Input
                                                size='sm'
                                                labelPlaceholder="E-mail"
                                                status="default"
                                                clearable
                                            />
                                        </Col>
                                        <Col xs={12} md={6}>
                                            <Input
                                                size='sm'
                                                labelPlaceholder="Nome de exibição"
                                                status="default"
                                                clearable
                                            />
                                        </Col>
                                    </Row>
                                    <Row className='py-3'>
                                        <Col xs={12} md={6}>
                                            <Input.Password
                                                size='sm'
                                                labelPlaceholder="Senha"
                                                status="default"
                                                clearable
                                            />
                                        </Col>
                                        <Col xs={12} md={6}>
                                            <Input.Password
                                                size='sm'
                                                labelPlaceholder="Confirmar senha"
                                                status="default"
                                                clearable
                                            />
                                        </Col>
                                    </Row>
                                    <Row className='py-3'>
                                        <Col sm={12} md={6}>
                                            <Dropdown>
                                                <Dropdown.Button size="sm" flat color="primary" className={text.small_regular_label}>
                                                    {selected}
                                                </Dropdown.Button>
                                                <Dropdown.Menu
                                                    aria-label="Single selection actions"
                                                    color="primary"
                                                    disallowEmptySelection
                                                    selectionMode="single"
                                                    selectedKeys={option}
                                                    onSelectionChange={setSelected}
                                                >
                                                    <Dropdown.Item key="Feminino">Feminino</Dropdown.Item>
                                                    <Dropdown.Item key="Masculino">Masculino</Dropdown.Item>
                                                    <Dropdown.Item key="Outro">Outro</Dropdown.Item>
                                                    <Dropdown.Item key="Prefiro não informar">Prefiro não informar</Dropdown.Item>
                                                </Dropdown.Menu>
                                            </Dropdown>
                                        </Col>
                                        <Col xs={12} md={6}>
                                            <Button
                                                auto
                                                size="sm"
                                                css={{ backgroundColor: '$gray', color: '#697177' }}
                                                className={text.small_regular_label}
                                                icon={<UploadIcon fill="#697177" filled />}
                                            >Selecione uma foto</Button>
                                        </Col>
                                    </Row>
                                    <Row className='py-4 mt-4'>
                                        <Col md={12} className='d-flex justify-content-center'>
                                            <Button rounded size="sm" color='secondary'>Cadastrar</Button>
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col md={12} className='d-flex justify-content-center align-items-center px-0 mx-0' >
                                            <span className={text.small_regular}>Já está cadastrado?</span><CustomLink href='/login' className='px-1'>Faça login</CustomLink>
                                        </Col>
                                    </Row>
                                </Col>
                            </Row>

                        </Col>
                        <Col md={4} className={`${container.image_background_cadastro} align-items-center d-none d-md-flex`}>
                            <Image width={606} height={466.95} src='/story_teller_logo_compacto_sombreado.svg' alt='logo Story Teller' />
                        </Col>
                        <Col xs={12} className={`justify-content-center d-flex d-md-none`}>
                            <Image width={200} height={153.69} src='/story_teller_logo_compacto.svg' alt='logo Story Teller' />
                        </Col>
                    </Row>
                </Container>
            </main>
        </>

    )
}
