import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/Components/Header'
import container from '@/styles/Containers.module.css'
import { Col, Container, Row } from 'reactstrap'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Story Teller</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/storyicon.ico" />
      </Head>
      <main>
        <Header type="index"/>
        <Container fluid className={`${container.container_lading_page} d-flex justify-content-center align-items-center`}>
          <Row>
            <Col>
            <Image width={1144} height={386} src='/Story Teller.svg' alt='logo Story Teller'/>
            </Col>
          </Row>
        </Container>
      </main>
    </>
  )
}
