import Head from 'next/head'
import React from 'react'
import { Col, Container, InputGroup, Row, Button } from 'reactstrap'
import container from '@/styles/Containers.module.css'
import text from '@/styles/Texts.module.css'
import input from '@/styles/Inputs.module.css'
import buttons from '@/styles/Buttons.module.css'
import Image from 'next/image'
import { Checkbox, Input, Spacer } from '@nextui-org/react'
import Link from 'next/link'
import { CustomLink } from '@/Components/Texts'
import { useRouter } from 'next/router'

function Login() {
    const router = useRouter()
    return (
        <>
            <Head>
                <title>Story Teller</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/storyicon.ico" />
            </Head>
            <main>
                <Container fluid className={container.container_black}>
                    <Row className='h-100'>
                        <Col xs={12} md={8} className='d-flex flex-column align-items-center justify-content-center'>
                            <Row className='justify-content-center my-4'>
                                <Col>
                                    <span className={text.title_white}>Faça seu Log-in</span>
                                </Col>
                            </Row>
                            <Row className='justify-content-center'>
                                <Col xs={10}>
                                    <Row className='py-4'>
                                        <Col className='d-flex flex-column justify-content-center align-items-center'>
                                            <Input
                                                width='100%'
                                                labelPlaceholder="E-mail"
                                                status="default"
                                                clearable
                                            />
                                            <Spacer y={2} />
                                            <Input.Password
                                                width='100%'
                                                labelPlaceholder="Senha"
                                                status="default"
                                                clearable
                                            />
                                        </Col>
                                    </Row>
                                    <Row className='py-2'>
                                        <Col className='px-3'>
                                            <Checkbox color='secondary' className={text.small_regular}>
                                                Lembre-se de mim
                                            </Checkbox>
                                        </Col>
                                    </Row>
                                    <Row className='py-2'>
                                        <Col md={12} className='d-flex justify-content-center'>
                                            <Button rounded size="md" className={`${buttons.darkRed} ${buttons.general}`} onClick={() => router.push('/dashboard')}>Entrar</Button>
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col md={12} className='d-flex justify-content-center align-items-center px-0 mx-0 pt-2' >
                                            {/* <span className={text.small_regular}>Não possui login?<Link className={`${text.links}, ${text.small_semiBold}`} href="/login" color="green"> Cadastre-se</Link></span> */}
                                            <span className={text.small_regular}>Não possui login?</span><CustomLink href='/cadastro' className={`${text.small_regular} px-1`}>Cadastre-se</CustomLink>
                                        </Col>
                                    </Row>
                                </Col>
                            </Row>

                        </Col>
                        <Col md={4} className={`${container.image_background_login} align-items-center d-none d-md-flex`}>
                            <Image width={606} height={466.95} src='/story_teller_logo_compacto_sombreado.svg' alt='logo Story Teller' />
                        </Col>
                        <Col xs={12} className={`justify-content-center d-flex d-md-none`}>
                            <Image width={200} height={153.69} src='/story_teller_logo_compacto.svg' alt='logo Story Teller' />
                        </Col>
                    </Row>
                </Container>
            </main>
        </>

    )
}

export default Login